### ISSUE TITLE
A little question about How does it works?

### ISSUE THREAD

**Issue by zqdeepbluesky** [lars76/kmeans-anchor-boxes#5]
@lars76 
Hi,how are you.the code works very well,But I still confused about how does it works.
for example the results:
AP = 0.67
K=5
[[0.792 0.776 ] 
[0.098 0.16516517] 
[0.042 0.07466667] 
[0.38133333 0.52535323] 
[0.184 0.33866667]]
what does these [[0.792 0.776 ] ,[0.098 0.16516517] ...] mean?Are they refer to the width and height of the anchors,?How to get these anchors's width and height And why in the yolo9000 these wight and height are some coordinates? for example(10x13),(16x30),(33x23),(30x61),(62x45)...
Can you teach me about that？
thanks so much and Happy Dragon Boat Festival。

**Comment by lars76** [comment]
Hi,

the coordinates are the normalized anchors, because the images are of different sizes. Before the algorithm is started, we divide the coordinates by the image size (line 20 - 24 in example.py).

In YOLOv3 the authors decided to predict the boxes at 3 different scales. So the 9 clusters from YOLO have to be multiplied by some constants x, y, z:

scale x: (10×13),(16×30),(33×23)
scale y: (30×61),(62×45),(59×119)
scale z: (116 × 90),(156 × 198),(373 × 326).

If you look at YOLOv2 the situation is different: https://github.com/pjreddie/darknet/blob/6e7914530939aeaa4e6cc1a692b15e23d5173ae0/cfg/yolo-voc.2.0.cfg. The anchors are 1.08,1.19,  3.42,4.41,  6.63,11.38,  9.42,5.11,  16.62,10.52. But you have to still multiply the coordinates by some constant. This depends on the size of your grid.

端午节快乐 to you too

**Comment by zqdeepbluesky** [comment]
hi, thanks for your help,now I know.But if I want to draw these points on the graph with python, can I use these points directly as coordinates?
such as use these width and height:
`[[0.792 0.776 ] 
[0.098 0.16516517] 
[0.042 0.07466667] 
[0.38133333 0.52535323] 
[0.184 0.33866667]] 
`

**Comment by lars76** [comment]
Yes, you can use them directly. However, it might not be so useful as a function f(0.0792) = 0.0776 etc. As points it makes more sense (0.0792, 0), (0.0792, 0.776), (0, 0), (0, 0.776) etc. Then you get all the boxes

**Comment by zqdeepbluesky** [comment]
Thanks so much for your answers,now I know use box show these points is more meaningful.And I wonder If I want to plot the k-means anchors before and after clustering using matplotlib, as the k-means algorithm does, can you tell Me what I should do? Really very thankful and wish you a nice day.

**Comment by lars76** [comment]
What you could do is: print(clusters) before while True: in kmeans.py to get the anchors before clustering. Then copy the anchors before and after clustering in a new file and use matplotlib.patches.Rectangle to plot each of the clusters. I would change the color also because all the rectangles will start at the point (0,0) due to normalization.

**Comment by zqdeepbluesky** [comment]
Hi, thanks so much, I will do it,did you try it yet?

**Comment by lars76** [comment]
No, because I'm pretty sure that the algorithm works correctly. So I never verified it geometrically, but if you want to do, it should be only a few lines of code.

**Comment by zqdeepbluesky** [comment]
You are right,  I want to visualization it cause it can help me to understand the algorithm deeply.
thanks so much for trouble you.have a nice day:)

**Comment by twmht** [comment]
@lars76 

I have one more question about yolov3, 

Since yolov3 have 3 scales, if I use k-means to find 9 clusters, does this mean at each scale there are 9 anchors?

In the yolov3.cfg (https://github.com/pjreddie/darknet/blob/master/cfg/yolov3.cfg), they have 3 anchors at each scale, does this mean they use k-means to find only 3 clusters? But they use different ratios at each scale?
